AWS Device Farm

diff --git a/.github/templates/main.yml b/.github/templates/main.yml
--- a/.github/templates/main.yml
+++ b/.github/templates/main.yml
@@ -1,6 +1,6 @@
 #@ load("@ytt:template", "template")
 #@ load("@ytt:overlay", "overlay")
-#@ load("common.lib.yml", "configuration", "nugetPackages", "checkoutCode", "setupVcpkg", "actionCache", "actionUploadArtifact", "actionDownloadArtifact", "actionSetupMSBuild", "actionSetupDotnet", "actionRuniOSSimulator", "actionDockerLayerCaching", "actionDockerBuild", "actionDockerRun", "actionCoveralls", "actionDeleteArtifact", "actionDeployBaaS", "actionCleanupBaaS", "readVersionFromPackage", "uploadPackagesToSleet", "cleanupWorkspace")
+#@ load("common.lib.yml", "configuration", "nugetPackages", "checkoutCode", "setupVcpkg", "actionCache", "actionUploadArtifact", "actionDownloadArtifact", "actionSetupMSBuild", "actionSetupDotnet", "actionRuniOSSimulator", "actionDockerLayerCaching", "actionDockerBuild", "actionDockerRun", "actionCoveralls", "actionDeleteArtifact", "actionDeployBaaS", "actionCleanupBaaS", "readVersionFromPackage", "uploadPackagesToSleet", "cleanupWorkspace", "configureAWSCredentials")
 
 #@ isRelease = "contains(github.head_ref, 'release')"
 
@@ -213,53 +213,65 @@ steps:
 #@ end
 
 #@ def xamarinAndroidTestSteps():
-  - #@ msbuild("Tests/Tests.Android", target="SignAndroidPackage", AndroidSupportedAbis="x86_64", AndroidUseSharedRuntime="False", EmbedAssembliesIntoApk="True", RestoreConfigFile="Tests/Test.NuGet.Config", UseRealmNupkgsWithVersion="${{ needs.build-packages.outputs.package_version }}")
-  - name: AVD cache
-    uses: actions/cache@v2
-    id: avd-cache
-    with:
-      path: |
-        ~/.android/avd/*
-        ~/.android/adb*
-      key: android-avd
-  - name: Create AVD for caching
-    if: steps.avd-cache.outputs.cache-hit != 'true'
-    uses: reactivecircus/android-emulator-runner@v2
-    with:
-      api-level: 29
-      arch: x86_64
-      force-avd-creation: false
-      emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-      disable-animations: false
-      script: echo "Generated AVD snapshot for caching."
+  - #@ template.replace(msbuildOnWin("Tests/Tests.Android", target="SignAndroidPackage", AndroidSupportedAbis="armeabi-v7a", AndroidUseSharedRuntime="False", EmbedAssembliesIntoApk="True"))
+  - #@ template.replace(configureAWSCredentials("AWS_DEVICEFARM_ACCESS_KEY_ID", "AWS_DEVICEFARM_SECRET_ACCESS_KEY", "us-west-2"))
   - name: Run the tests
-    uses: reactivecircus/android-emulator-runner@v2
+    uses: aardsoft/aws-devicefarm/test-application@master
+    id: run_tests
     with:
-      api-level: 29
-      arch: x86_64
-      force-avd-creation: false
-      emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
-      disable-animations: true
+      file_artifacts: |
+        Customer Artifacts.zip
+        Logcat.logcat
+      project_arn: ${{ secrets.DEVICEFARM_PROJECT_ARN }}
+      device_pool_arn: ${{ secrets.DEVICEFARM_ANDROID_POOL_ARN }}
+      app_file: ${{ github.workspace }}/Tests/Tests.Android/bin/Release/io.realm.xamarintests-Signed.apk
+      app_type: ANDROID_APP
+      test_type: APPIUM_PYTHON
+      test_package_file: https://github.com/aardsoft/aws-devicefarm-sample-data/releases/download/0.3/sample_env_python3.zip
+      test_package_type: APPIUM_PYTHON_TEST_PACKAGE
+      test_spec_file: test_spec.yaml
+      test_spec_type: APPIUM_PYTHON_TEST_SPEC
       #@yaml/text-templated-strings
-      script: |
-        adb devices
-        adb logcat -c
-        adb logcat -v time > "${{ github.workspace }}/logcat.txt" &
+      test_spec: |
+        version: 0.1
+        phases:
+          install:
+            commands:
+              - export PYTHON_VERSION=3
 
-        adb install ${{ github.workspace }}/Tests/Tests.Android/bin/Release/io.realm.xamarintests-Signed.apk
-        adb shell pm grant io.realm.xamarintests android.permission.READ_EXTERNAL_STORAGE
-        adb shell pm grant io.realm.xamarintests android.permission.WRITE_EXTERNAL_STORAGE
+          pre_test:
+            commands:
+              - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.xamarintests android.permission.READ_EXTERNAL_STORAGE
+              - adb -s $DEVICEFARM_DEVICE_UDID shell pm grant io.realm.xamarintests android.permission.WRITE_EXTERNAL_STORAGE
 
-        echo "--baasurl=(@= secret_BaseUrl @) --baascluster=${{ env.CLUSTER_NAME }} --baasapikey=(@= secret_AtlasPublicKey @) --baasprivateapikey=(@= secret_AtlasPrivateKey @) --baasprojectid=(@= secret_AtlasProjectId @)" > ${{ github.workspace }}/testargs.txt
-        adb push ${{ github.workspace }}/testargs.txt /storage/emulated/0/RealmTests/testargs.txt
+          test:
+            commands:
+              - echo "--baasurl=(@= secret_BaseUrl @) --baascluster=${{ env.CLUSTER_NAME }} --baasapikey=(@= secret_AtlasPublicKey @) --baasprivateapikey=(@= secret_AtlasPrivateKey @) --baasprojectid=(@= secret_AtlasProjectId @)" > testargs.txt
+              - adb -s $DEVICEFARM_DEVICE_UDID push testargs.txt /storage/emulated/0/RealmTests/testargs.txt
+              - adb -s $DEVICEFARM_DEVICE_UDID shell am instrument -w -r io.realm.xamarintests/.TestRunner
 
-        adb shell am instrument -w -r io.realm.xamarintests/.TestRunner
-        adb pull /storage/emulated/0/RealmTests/TestResults.Android.xml ${{ github.workspace }}/TestResults.Android.xml
-        adb shell rm /sdcard/Realmtests/TestResults.Android.xml
-  - name: Output logcat
-    if: always()
-    run: cat logcat.txt
-  - #@ publishTestsResults("TestResults.Android.xml", "Xamarin.Android")
+          post_test:
+            commands:
+              - adb -s $DEVICEFARM_DEVICE_UDID pull /storage/emulated/0/RealmTests/TestResults.Android.xml $DEVICEFARM_LOG_DIR/TestResults.Android.xml
+
+        artifacts:
+          - $DEVICEFARM_LOG_DIR
+      remote_src: true
+  - run: |
+      dir
+      Expand-Archive 'Customer Artifacts.zip' -DestinationPath artifacts
+      echo "::group::Logcat"
+      cat Logcat.logcat
+      echo "::endgroup::"
+    name: Fetch test artifacts
+  - run: |
+      echo "::group::Data"
+      echo (ConvertFrom-Json '${{ steps.run_tests.outputs.data }}' | ConvertTo-Json)
+      echo "::endgroup::"
+      exit 1
+    if: steps.run_tests.outputs.data.run.result != 'PASSED'
+    name: Failed run
+  - #@ publishTestsResults("artifacts/Host_Machine_Files/$DEVICEFARM_LOG_DIR/TestResults.Android.xml", "Xamarin.Android")
 #@ end
 
 #@ def codeCoverageTestSteps():
@@ -622,7 +634,7 @@ jobs:
       - #@ publishTestsResults("TestResults.xml", ".NET (${{ matrix.os }}, ${{ matrix.targetFramework }})")
   _: #@ template.replace(testJob("Xamarin.macOS", "macos-latest", xamarinMacTestSteps()))
   _: #@ template.replace(testJob("Xamarin.iOS", "macos-latest", xamariniOSTestSteps()))
-  _: #@ template.replace(testJob("Xamarin.Android", "macos-latest", xamarinAndroidTestSteps()))
+  _: #@ template.replace(testJob("Xamarin.Android", "windows-latest", xamarinAndroidTestSteps()))
   run-tests-xunit:
     runs-on: windows-latest
     name: Test xUnit Compatibility
